package:
  name: rmnd-lca
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - wurst
    - numpy
    - pandas
    - bw2io
    - bw2data
    - xarray
    - pytest
    - pytest-cov
    - coveralls
    - setuptools
    - prettytable
    - carculator
  run:
    - python
    - wurst
    - numpy
    - pandas
    - bw2io
    - bw2data
    - xarray
    - prettytable
    - carculator

test:
  imports:
    - rmnd_lca

about:
  home: https://github.com/romainsacchi/rmnd-lca
  license: BSD License
  summary: 'Coupling REMIND output to ecoinvent LCA databases.'
license_family: BSD
